# Changement du port
server.port=8084

# Configuration MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/Crowdfunding_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# Configuration Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Pour voir les changements HTML sans red\u00e9marrer (Optionnel)
spring.thymeleaf.cache=false
stripe.api.key=sk_test_51TQXj7CME3TEkn4Ixyh1J06zqoOeoQnAONtzLcuI13ZJrS4Uh3hThHmXOUp0Ks7rKTzX1Gz9VzBSAGhiCP62FpWx00ypTr4HKZ